plugins {
    id 'java'
    id 'org.jetbrains.intellij.platform' version '2.18.1'
}

group = 'com.andrew-volostnykh.intelli.webrunner'
version = '1.0.0'

repositories {
    mavenLocal()
    maven {
        url = uri('https://maven.pkg.github.com/AndrewVolostnykh/Intelli-Webrunner')
        credentials {
            username = findProperty('gpr.user') ?: System.getenv('GITHUB_ACTOR')
            password = findProperty('gpr.key') ?: System.getenv('GITHUB_TOKEN')
        }
    }
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

intellijPlatform {
    instrumentCode = false
}

patchPluginXml {
    sinceBuild = '242'
    untilBuild = null
}

dependencies {
    implementation 'com.andrew-volostnykh.webrunner:webrunner-core:1.0.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation 'io.grpc:grpc-netty-shaded:1.63.0'
    implementation 'io.grpc:grpc-protobuf:1.63.0'
    implementation 'io.grpc:grpc-stub:1.63.0'
    implementation 'io.grpc:grpc-services:1.63.0'
    implementation 'com.google.protobuf:protobuf-java-util:3.25.3'
    implementation 'org.apache.kafka:kafka-clients:3.7.1'
    implementation 'org.mozilla:rhino:1.7.14'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    intellijPlatform {
        intellijIdeaUltimate('2024.2.3')
        bundledPlugin('com.intellij.java')
    }
}

processResources {
    from('docs') {
        into 'docs'
        include '*.md'
    }
}

test {
    useJUnitPlatform()
}
